[Interface]
PrivateKey = WINE8Q7NTjIcTw0n672pikrirfAks+a5rPLckF50ank=
Address = 10.50.0.11/32
ListenPort = 51830

[Peer]
PublicKey = hjn08rv9btOYyo7tRPziUx0xP1+xnP23Law7W7u+Ugk=
AllowedIPs = 10.50.0.1/32
Endpoint = 10.50.0.1:51820
PersistentKeepalive = 25

[Peer]
PublicKey = ZakqiVIV0sGeDbK2vgrpMYYQd4lMf36LfTZjokp66mM=
AllowedIPs = 10.50.0.2/32
Endpoint = 10.50.0.2:51821
PersistentKeepalive = 25

[Peer]
PublicKey = t+uq7/vL27EmCYSoOCnL+9trpQCNz1jRYmnC7AGZyWQ=
AllowedIPs = 10.50.0.3/32
Endpoint = 10.50.0.3:51822
PersistentKeepalive = 25

[Peer]
PublicKey = FqMsFwDia0sa2daf82vOw0LptXyozaugdKi9SpYGbwg=
AllowedIPs = 10.50.0.4/32
Endpoint = 10.50.0.4:51823
PersistentKeepalive = 25

[Peer]
PublicKey = d8Bc9DhNZ1YD641OFfj3HDoeTD2FCvBGqeNslTPCmTE=
AllowedIPs = 10.50.0.5/32
Endpoint = 10.50.0.5:51824
PersistentKeepalive = 25

[Peer]
PublicKey = +xzRuFKcrALj8MsTWhF3sLZNw+HZIPvH8uREre01UH0=
AllowedIPs = 10.50.0.6/32
Endpoint = 10.50.0.6:51825
PersistentKeepalive = 25

[Peer]
PublicKey = GoxiBgVVHCcV4P6iHOWV+RnnEI8Q/3KX98HW1uw1BG4=
AllowedIPs = 10.50.0.7/32
Endpoint = 10.50.0.7:51826
PersistentKeepalive = 25

[Peer]
PublicKey = +xzEIK/T0D7NFm/w9nY9y3uIHsjYFwEeeWAkXl/niiE=
AllowedIPs = 10.50.0.8/32
Endpoint = 10.50.0.8:51827
PersistentKeepalive = 25

[Peer]
PublicKey = OAZ1PCbO2WMZzGZtkPkJS0gqHrRw/2q7oy0Dw/ag9kw=
AllowedIPs = 10.50.0.9/32
Endpoint = 10.50.0.9:51828
PersistentKeepalive = 25

[Peer]
PublicKey = blLCKI1VRctnnCDc5rwLTldI03lEt2bULL+ujKCH8x8=
AllowedIPs = 10.50.0.10/32
Endpoint = 10.50.0.10:51829
PersistentKeepalive = 25

[Peer]
PublicKey = JZPft26jnFLHJHO545EnEZEJIxpzWC3ks4chRIt7cEU=
AllowedIPs = 10.50.0.12/32
Endpoint = 10.50.0.12:51831
PersistentKeepalive = 25

[Peer]
PublicKey = 0N/Ug4ehYqHnzt2VRGc0/tdqPbYl9Jk0v7T15OgCPBA=
AllowedIPs = 10.50.0.13/32
Endpoint = 10.50.0.13:51832
PersistentKeepalive = 25

