#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
INVENTORY_FILE="$ROOT_DIR/devnet/lean15/node-inventory.csv"
OUTPUT_FILE="${1:-$ROOT_DIR/devnet/lean15/hosts.env}"
ORCHESTRATOR_SCRIPT="$ROOT_DIR/scripts/devnet15/remote-node-orchestrator.sh"

if [[ ! -f "$INVENTORY_FILE" ]]; then
  echo "Inventory file missing: $INVENTORY_FILE" >&2
  exit 1
fi

if [[ ! -x "$ORCHESTRATOR_SCRIPT" ]]; then
  echo "Orchestrator script missing or not executable: $ORCHESTRATOR_SCRIPT" >&2
  exit 1
fi

mkdir -p "$(dirname "$OUTPUT_FILE")"
if [[ -f "$OUTPUT_FILE" ]]; then
  backup="$OUTPUT_FILE.bak.$(date -u +%Y%m%dT%H%M%SZ)"
  cp "$OUTPUT_FILE" "$backup"
  echo "Backed up existing hosts.env to: $backup"
fi

cat > "$OUTPUT_FILE" <<HEADER
# Auto-generated by scripts/devnet15/generate-monitor-hosts-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# This file powers the Synergy Devnet Control Panel app remote orchestration workflow.
#
# Global SSH defaults used by remote-node-orchestrator.sh:
SYNERGY_DEVNET_SSH_USER=ops
SYNERGY_DEVNET_SSH_PORT=22
# Optional global SSH private key path:
# SYNERGY_DEVNET_SSH_KEY=/Users/you/.ssh/id_ed25519
SYNERGY_DEVNET_WG_HUB_PUBLIC_IP=64.227.107.57
SYNERGY_DEVNET_WG_HUB_VPN_IP=10.50.0.254
SYNERGY_DEVNET_WG_HUB_PORT=51820

# Explorer bridge used by control panel Atlas links:
ATLAS_BASE_URL=https://devnet-explorer.synergy-network.io
SYNERGY_EXPLORER_RESET_ENDPOINT=https://devnet-atlas-api.synergy-network.io/v1/admin/reindex-from-genesis

HEADER

while IFS=, read -r node_slot_id node_alias role_group role node_type _ _ _ _ _ _ host vpn_ip _ _ _ || [[ -n "${node_slot_id:-}" ]]; do
  [[ "$node_slot_id" == "node_slot_id" ]] && continue
  [[ -z "${node_slot_id:-}" ]] && continue

  node_slot_key="$(printf '%s' "$node_slot_id" | tr '[:lower:]-' '[:upper:]_')"

  if [[ -z "${host:-}" ]]; then
    host="$vpn_ip"
  fi

  cat >> "$OUTPUT_FILE" <<ENTRY
# -----------------------------------------------------------------------------
# $node_slot_id ($node_alias | $role_group | $role | $node_type)
${node_slot_key}_HOST=$host
${node_slot_key}_VPN_IP=$vpn_ip
${node_slot_key}_SSH_USER=ops
${node_slot_key}_SSH_PORT=22
# ${node_slot_key}_SSH_KEY=
# ${node_slot_key}_REMOTE_DIR=/opt/synergy/$node_slot_id

${node_slot_key}_START_CMD="$ORCHESTRATOR_SCRIPT $node_slot_id start"
${node_slot_key}_STOP_CMD="$ORCHESTRATOR_SCRIPT $node_slot_id stop"
${node_slot_key}_RESTART_CMD="$ORCHESTRATOR_SCRIPT $node_slot_id restart"
${node_slot_key}_STATUS_CMD="$ORCHESTRATOR_SCRIPT $node_slot_id status"
${node_slot_key}_SETUP_CMD="$ORCHESTRATOR_SCRIPT $node_slot_id setup_node"
${node_slot_key}_EXPORT_LOGS_CMD="$ORCHESTRATOR_SCRIPT $node_slot_id export_logs"
${node_slot_key}_VIEW_CHAIN_DATA_CMD="$ORCHESTRATOR_SCRIPT $node_slot_id view_chain_data"
${node_slot_key}_EXPORT_CHAIN_DATA_CMD="$ORCHESTRATOR_SCRIPT $node_slot_id export_chain_data"

${node_slot_key}_ACTION_INSTALL_NODE_CMD="$ORCHESTRATOR_SCRIPT $node_slot_id install_node"
${node_slot_key}_ACTION_BOOTSTRAP_NODE_CMD="$ORCHESTRATOR_SCRIPT $node_slot_id bootstrap_node"
${node_slot_key}_ACTION_NODE_LOGS_CMD="$ORCHESTRATOR_SCRIPT $node_slot_id logs"
${node_slot_key}_ACTION_RESET_CHAIN_CMD="$ORCHESTRATOR_SCRIPT $node_slot_id reset_chain"

ENTRY

done < "$INVENTORY_FILE"

echo "Generated monitor hosts config: $OUTPUT_FILE"
