export const FEATURE_SCREEN_GROUPS = [
  {
    id: 'monitor',
    label: 'Monitor',
    items: [
      'alerts',
    ],
  },
  {
    id: 'validator',
    label: 'Validator',
    items: [
      'validator',
      'security',
      'identity',
    ],
  },
  {
    id: 'protocol',
    label: 'Protocol',
    items: [
      'consensus',
      'dag',
      'transactions',
    ],
  },
  {
    id: 'system',
    label: 'System',
    items: [
      'storage',
      'api',
      'maintenance',
      'diagnostics',
      'config',
    ],
  },
];

export const FEATURE_SCREENS = {
  alerts: {
    key: 'alerts',
    path: '/alerts',
    icon: 'notification_important',
    label: 'Alerts',
    title: 'Incident Response & Alerts',
    eyebrow: 'Action center',
    description: 'Prioritized alerts, runbooks, and emergency response controls for unsafe node states.',
    jarvis: 'This screen answers what needs attention next. Critical alerts stay above the fold and each one points to a runbook or isolation workflow.',
    tone: 'warn',
    modeCopy: {
      basic: 'Plain-language alerts, recommended actions, and safe next steps.',
      advanced: 'Alert routing, incident severity, runbook assignment, and event correlation.',
      developer: 'Alert payloads, trigger sources, automation receipts, and incident bundle controls.',
    },
    questions: [
      { label: 'Am I safe?', value: 'Watch active alerts', tone: 'warn', icon: 'health_and_safety' },
      { label: 'Am I participating correctly?', value: 'No missed duties', tone: 'good', icon: 'how_to_reg' },
      { label: 'What should I do next?', value: 'Review runbooks', tone: 'cyan', icon: 'rule' },
    ],
    metrics: [
      { label: 'Critical alerts', value: '2', detail: 'Require operator review', tone: 'bad', icon: 'report' },
      { label: 'Warnings', value: '5', detail: 'Deduplicated by source', tone: 'warn', icon: 'warning' },
      { label: 'Mean recovery', value: '15m', detail: 'Last 24 hours', tone: 'cyan', icon: 'timer' },
      { label: 'Acknowledged', value: '71%', detail: 'Within policy', tone: 'good', icon: 'task_alt' },
    ],
    checklistTitle: 'Suggested runbooks',
    checklist: [
      { label: 'Restart signer node', detail: 'Signer offline alert remains active.', done: false, tone: 'bad' },
      { label: 'Mitigate slashing risk', detail: 'Duplicate signer guard should stay locked.', done: true, tone: 'good' },
      { label: 'Scale network resources', detail: 'Peer latency warning crossed threshold.', done: false, tone: 'warn' },
      { label: 'Deploy software update', detail: 'Required version policy is available.', done: false, tone: 'cyan' },
    ],
    tableTitle: 'Active incident stream',
    tableColumns: ['Severity', 'Signal', 'Source', 'Age'],
    tableRows: [
      ['Critical', 'Signer offline', 'remote-signer', '2m'],
      ['Critical', 'Consensus finality delay', 'consensus', '7m'],
      ['Warning', 'Peer diversity low', 'p2p', '14m'],
      ['Info', 'Snapshot completed', 'storage', '31m'],
    ],
    visual: 'alerts',
    actions: [
      { id: 'acknowledge-alerts', label: 'Acknowledge Reviewed Alerts', variant: 'blue' },
      { id: 'export-incident-bundle', label: 'Export Incident Bundle', variant: 'purple' },
    ],
  },
  validator: {
    key: 'validator',
    path: '/validator',
    icon: 'verified_user',
    label: 'Validator',
    title: 'Validator Lifecycle Management',
    eyebrow: 'Validator safety',
    description: 'Registration, activation, duty scheduling, performance, exit workflows, and irreversible-action guardrails.',
    jarvis: 'Validator actions are separated from normal node operations because signing, activation, unbonding, and exit workflows have irreversible safety consequences.',
    tone: 'purple',
    modeCopy: {
      basic: 'Simple validator status, upcoming duties, and guided safety checks.',
      advanced: 'Lifecycle stages, duty calendar, performance benchmarks, and stake-position checks.',
      developer: 'Raw validator identity, duty windows, last signed units, and migration guards.',
    },
    questions: [
      { label: 'Lifecycle', value: 'Active', tone: 'good', icon: 'verified' },
      { label: 'Duties', value: '2 upcoming', tone: 'cyan', icon: 'event' },
      { label: 'Risk', value: 'Guarded', tone: 'good', icon: 'shield' },
    ],
    metrics: [
      { label: 'Voting uptime', value: '99.8%', detail: 'Last 7 days', tone: 'good', icon: 'how_to_vote' },
      { label: 'Missed duties', value: '1', detail: 'Proposal window clear', tone: 'warn', icon: 'event_busy' },
      { label: 'Stake weight', value: '4.5%', detail: 'Validator set share', tone: 'purple', icon: 'stacked_line_chart' },
      { label: 'Activation', value: 'Epoch 5', detail: 'Current duty epoch', tone: 'cyan', icon: 'flag' },
    ],
    checklistTitle: 'Validator readiness checklist',
    checklist: [
      { label: 'Slashing database present', detail: 'Last signed state is available.', done: true, tone: 'good' },
      { label: 'Clock drift under threshold', detail: 'Local time source is healthy.', done: true, tone: 'good' },
      { label: 'Remote signer reachable', detail: 'TLS and latency checks passed.', done: true, tone: 'good' },
      { label: 'Backup node sync verified', detail: 'Backup is near enough for safe promotion.', done: false, tone: 'warn' },
    ],
    tableTitle: 'Duty calendar',
    tableColumns: ['Duty', 'Window', 'Status', 'Action'],
    tableRows: [
      ['Checkpoint vote', '14m 35s', 'Ready', 'Monitor'],
      ['DAG vertex production', '02h 12m', 'Ready', 'Monitor'],
      ['Epoch transition', '14h 05m', 'Low risk', 'Schedule'],
      ['Proposal slot', '1d 02h', 'Clear', 'Plan'],
    ],
    visual: 'lifecycle',
    danger: {
      title: 'Danger zone',
      copy: 'Unbonding, forced exit, and identity migration can interrupt rewards or permanently remove a validator from active participation.',
      confirmLabel: 'Open validator action review',
    },
    actions: [
      { id: 'run-validator-preflight', label: 'Run Validator Preflight', variant: 'lime' },
      { id: 'open-duty-calendar', label: 'Open Duty Calendar', variant: 'blue' },
    ],
  },
  consensus: {
    key: 'consensus',
    path: '/consensus',
    icon: 'account_tree',
    label: 'Consensus',
    title: 'Consensus & Finality Monitoring',
    eyebrow: 'Hybrid finality',
    description: 'Consensus rounds, quorum participation, finality lag, checkpoint timing, and validator duty health.',
    jarvis: 'This page separates linear chain finality from DAG activity so operators can see whether participation and ordering are healthy.',
    tone: 'cyan',
    modeCopy: {
      basic: 'Readable finality status, current duty, and whether the node is participating correctly.',
      advanced: 'Rounds, quorum thresholds, finalized head, safe head, and duty inclusion latency.',
      developer: 'Consensus message rates, vote inclusion, checkpoint signatures, and fork-choice diagnostics.',
    },
    questions: [
      { label: 'Current duty', value: 'Proposer', tone: 'cyan', icon: 'campaign' },
      { label: 'Quorum', value: '95%', tone: 'good', icon: 'groups' },
      { label: 'Finality lag', value: '1.2s', tone: 'good', icon: 'speed' },
    ],
    metrics: [
      { label: 'Epoch progress', value: '02h 35m', detail: 'Until next checkpoint', tone: 'cyan', icon: 'schedule' },
      { label: 'Vote inclusion', value: '98.6%', detail: 'Last 100 rounds', tone: 'good', icon: 'done_all' },
      { label: 'Timeouts', value: '0', detail: 'Current round', tone: 'good', icon: 'timer_off' },
      { label: 'Finalized head', value: '421,891', detail: 'Checkpoint chain', tone: 'purple', icon: 'link' },
    ],
    checklistTitle: 'Consensus safety checks',
    checklist: [
      { label: 'Connected validator ratio healthy', detail: 'Stake-weighted path is above threshold.', done: true, tone: 'good' },
      { label: 'Checkpoint signatures verified', detail: 'Latest finality proof is accepted.', done: true, tone: 'good' },
      { label: 'Fork-choice view aligned', detail: 'Local safe head agrees with network safe head.', done: true, tone: 'good' },
      { label: 'View-change rate normal', detail: 'No timeout burst in the current epoch.', done: true, tone: 'good' },
    ],
    tableTitle: 'Consensus timeline',
    tableColumns: ['Stage', 'Height', 'Role', 'Status'],
    tableRows: [
      ['Block', '421,891', 'Proposer', 'Included'],
      ['Vote', '421,890', 'Voter', 'Finalized'],
      ['Checkpoint', 'Epoch 5', 'Signer', 'Verified'],
      ['DAG anchor', 'Epoch 5', 'Aggregator', 'Ordering'],
    ],
    visual: 'consensus',
    actions: [
      { id: 'refresh-finality', label: 'Refresh Finality State', variant: 'blue' },
      { id: 'export-consensus-report', label: 'Export Consensus Report', variant: 'purple' },
    ],
  },
  dag: {
    key: 'dag',
    path: '/dag',
    icon: 'schema',
    label: 'DAG',
    title: 'DAG Topology & Graph View',
    eyebrow: 'Concurrency map',
    description: 'Tips, parents, conflicts, pruning points, branch convergence, and local-versus-network DAG view.',
    jarvis: 'The DAG view makes concurrency visible. It shows why vertices are finalized, pending, conflicting, delayed, or pruned.',
    tone: 'cyan',
    modeCopy: {
      basic: 'Plain DAG health, tip count, and whether transactions are converging.',
      advanced: 'Local versus network view, pruning point, conflict sets, orphan ratio, and finality zones.',
      developer: 'Replay controls, parent dependencies, topological order, branch convergence, and conflict graph inspection.',
    },
    questions: [
      { label: 'DAG width', value: '128', tone: 'cyan', icon: 'lan' },
      { label: 'Tip count', value: '24', tone: 'warn', icon: 'call_split' },
      { label: 'Convergence', value: '98.2%', tone: 'good', icon: 'merge' },
    ],
    metrics: [
      { label: 'Graph depth', value: '1.4M', detail: 'Accepted vertices', tone: 'cyan', icon: 'alt_route' },
      { label: 'Merge rate', value: '42/s', detail: 'Rolling window', tone: 'good', icon: 'merge_type' },
      { label: 'Conflict rate', value: '0.04%', detail: 'Policy rejected', tone: 'warn', icon: 'report_problem' },
      { label: 'Pruning point', value: 'Epoch 5', detail: 'Safe retention marker', tone: 'purple', icon: 'content_cut' },
    ],
    checklistTitle: 'DAG integrity checks',
    checklist: [
      { label: 'Missing parents resolved', detail: 'No unresolved parent references in the local view.', done: true, tone: 'good' },
      { label: 'Conflict sets isolated', detail: 'Conflicting branches remain outside finality zone.', done: true, tone: 'good' },
      { label: 'Peer view compared', detail: 'Network view drift is within tolerance.', done: true, tone: 'good' },
      { label: 'Pruning marker verified', detail: 'Retention boundary has a checkpoint anchor.', done: true, tone: 'good' },
    ],
    tableTitle: 'DAG node inspection',
    tableColumns: ['Vertex', 'State', 'Parents', 'Finality'],
    tableRows: [
      ['vtx-24a9', 'Finalized', '3', 'Checkpointed'],
      ['vtx-9c31', 'Accepted', '2', 'High confidence'],
      ['vtx-b117', 'Pending', '4', 'Awaiting parents'],
      ['vtx-f8d0', 'Conflicting', '2', 'Blocked'],
    ],
    visual: 'dag',
    actions: [
      { id: 'toggle-dag-view', label: 'Compare Local / Network', variant: 'blue' },
      { id: 'export-dag-replay', label: 'Export DAG Replay', variant: 'purple' },
    ],
  },
  transactions: {
    key: 'transactions',
    path: '/transactions',
    icon: 'swap_horiz',
    label: 'Transactions',
    title: 'Transactions, Mempool & DAG Pool',
    eyebrow: 'Transaction flow',
    description: 'Wallet actions, mempool pressure, DAG pool dependencies, transaction preview, and broadcast tools.',
    jarvis: 'This screen is the safe transaction workbench: preview before broadcast, inspect dependency state, and trace stuck transactions.',
    tone: 'cyan',
    modeCopy: {
      basic: 'Send, receive, and inspect transaction status in plain language.',
      advanced: 'Mempool pressure, dependency conflicts, fee strategy, and transaction replacement tools.',
      developer: 'Raw transaction decoding, local injection, signature verification, and pool policy diagnostics.',
    },
    questions: [
      { label: 'Pending txs', value: '1,204', tone: 'cyan', icon: 'pending_actions' },
      { label: 'DAG pool', value: '342', tone: 'purple', icon: 'schema' },
      { label: 'Rejections', value: '0.8%', tone: 'warn', icon: 'block' },
    ],
    metrics: [
      { label: 'Ingestion rate', value: '84/s', detail: 'Last minute', tone: 'cyan', icon: 'input' },
      { label: 'Inclusion latency', value: '2.1s', detail: 'Median', tone: 'good', icon: 'speed' },
      { label: 'Finality latency', value: '5.4s', detail: 'Hybrid finality', tone: 'good', icon: 'verified' },
      { label: 'Min fee', value: '0.02', detail: 'Current policy', tone: 'purple', icon: 'payments' },
    ],
    checklistTitle: 'Transaction safety preview',
    checklist: [
      { label: 'Destination address checked', detail: 'Address book and checksum passed.', done: true, tone: 'good' },
      { label: 'Fee strategy selected', detail: 'Dynamic fee estimate is inside policy.', done: true, tone: 'good' },
      { label: 'Nonce or sequence aligned', detail: 'No local sequence conflict detected.', done: true, tone: 'good' },
      { label: 'DAG dependencies clear', detail: 'No unresolved parent dependency.', done: true, tone: 'good' },
    ],
    tableTitle: 'Transaction pool sample',
    tableColumns: ['Hash', 'State', 'Pool', 'Reason'],
    tableRows: [
      ['0x24a9...1d', 'Pending', 'DAG pool', 'Waiting for parent'],
      ['0x99c1...e8', 'Accepted', 'Mempool', 'Included in candidate'],
      ['0x1b72...42', 'Finalized', 'Chain', 'Checkpointed'],
      ['0xf312...aa', 'Rejected', 'Policy', 'Low fee'],
    ],
    visual: 'flow',
    actions: [
      { id: 'open-transaction-preview', label: 'Open Transaction Preview', variant: 'blue' },
      { id: 'decode-raw-transaction', label: 'Decode Raw Transaction', variant: 'purple' },
    ],
  },
  storage: {
    key: 'storage',
    path: '/storage',
    icon: 'storage',
    label: 'Storage',
    title: 'Storage & Snapshot Management',
    eyebrow: 'State retention',
    description: 'Database growth, pruning safety, snapshot generation, archive policy, compaction, and restore readiness.',
    jarvis: 'Storage controls stay conservative. The panel warns before pruning, confirms snapshot trust, and keeps validator restore safety visible.',
    tone: 'cyan',
    modeCopy: {
      basic: 'Disk usage, backup age, and whether storage is healthy.',
      advanced: 'Pruning policy, snapshot schedule, archive coverage, and database maintenance.',
      developer: 'Store-level sizes, compaction, verification hashes, migration state, and restore-test receipts.',
    },
    questions: [
      { label: 'Disk forecast', value: '42.8 TB', tone: 'cyan', icon: 'stacked_line_chart' },
      { label: 'Pruning policy', value: 'Safe', tone: 'good', icon: 'rule' },
      { label: 'Backup', value: 'Healthy', tone: 'good', icon: 'backup' },
    ],
    metrics: [
      { label: 'State DB', value: '24 TB', detail: 'Current estimate', tone: 'cyan', icon: 'database' },
      { label: 'DAG DB', value: '14 TB', detail: 'Retention window', tone: 'purple', icon: 'schema' },
      { label: 'Logs', value: '1.0 TB', detail: '30 day retention', tone: 'warn', icon: 'receipt_long' },
      { label: 'Snapshots', value: '6', detail: 'Verified artifacts', tone: 'good', icon: 'inventory_2' },
    ],
    checklistTitle: 'Snapshot safety checks',
    checklist: [
      { label: 'Latest snapshot verified', detail: 'Hash and signature match release metadata.', done: true, tone: 'good' },
      { label: 'Archive responsibility checked', detail: 'Pruning will not remove required audit history.', done: true, tone: 'good' },
      { label: 'Restore drill scheduled', detail: 'Next restore drill is due this week.', done: false, tone: 'warn' },
      { label: 'Object storage credentials valid', detail: 'Upload target is reachable.', done: true, tone: 'good' },
    ],
    tableTitle: 'Storage breakdown',
    tableColumns: ['Area', 'Size', 'Policy', 'Status'],
    tableRows: [
      ['State database', '24 TB', 'Checkpoint pruning', 'Healthy'],
      ['DAG database', '14 TB', 'Epoch retention', 'Healthy'],
      ['Index database', '4 TB', 'Recent + archive', 'Watching'],
      ['Logs', '1 TB', '30 days', 'Healthy'],
    ],
    visual: 'storage',
    actions: [
      { id: 'generate-snapshot', label: 'Generate Snapshot', variant: 'lime' },
      { id: 'verify-backup', label: 'Verify Backup', variant: 'blue' },
    ],
  },
  security: {
    key: 'security',
    path: '/security',
    icon: 'shield',
    label: 'Identity + Security',
    title: 'Identity + Security',
    eyebrow: 'Operator safety',
    description: 'Node identity, key health, signer bridge, local hardening, slashing protection, and endpoint exposure in one operator screen.',
    jarvis: 'This is the screen operators should trust before signing. If identity, key health, endpoint exposure, or slashing protection is unsafe, signing should stay blocked.',
    modeLabels: {
      advanced: 'Identity + Security',
      developer: 'Security + Slashing',
    },
    modeTitles: {
      advanced: 'Identity + Security',
      developer: 'Security + Slashing',
    },
    tone: 'good',
    modeCopy: {
      basic: 'Clear safety status and whether signing is safe.',
      advanced: 'Slashing protection, doppelganger detection, file permissions, and endpoint exposure.',
      developer: 'Last signed units, signer leases, database integrity, certificate status, and hardening evidence.',
    },
    questions: [
      { label: 'Am I safe?', value: 'Safe', tone: 'good', icon: 'shield' },
      { label: 'Slashing DB', value: 'Active', tone: 'good', icon: 'database' },
      { label: 'Signer guard', value: 'Locked', tone: 'good', icon: 'lock' },
    ],
    metrics: [
      { label: 'Last height', value: '1,234,567', detail: 'Signed height', tone: 'good', icon: 'timeline' },
      { label: 'Slot', value: '5,678', detail: 'Last signed slot', tone: 'good', icon: 'view_timeline' },
      { label: 'Epoch', value: '256', detail: 'Last signed epoch', tone: 'good', icon: 'calendar_month' },
      { label: 'Protection', value: 'High', detail: 'Single-active-signer', tone: 'purple', icon: 'admin_panel_settings' },
    ],
    checklistTitle: 'Safe failover readiness',
    checklist: [
      { label: 'Backup node synced', detail: 'Backup height is inside the safe promotion window.', done: true, tone: 'good' },
      { label: 'Key management secure', detail: 'Signer policy and key storage pass checks.', done: true, tone: 'good' },
      { label: 'Failover script tested', detail: 'Last drill needs review before automatic failover.', done: false, tone: 'warn' },
      { label: 'Connectivity check passed', detail: 'No split-brain risk detected.', done: true, tone: 'good' },
    ],
    tableTitle: 'Security posture signals',
    tableColumns: ['Check', 'State', 'Evidence', 'Action'],
    tableRows: [
      ['Wrong network guard', 'Passed', 'Genesis hash verified', 'Monitor'],
      ['Duplicate process detection', 'Passed', 'One signer lease', 'Monitor'],
      ['Endpoint exposure', 'Watching', 'RPC auth required', 'Review'],
      ['Support bundle redaction', 'Passed', 'Secrets filtered', 'Export'],
    ],
    visual: 'security',
    danger: {
      title: 'Emergency stop signing',
      copy: 'This workflow halts validator signing and should be used only when slashing, key compromise, or wrong-network signing risk is credible.',
      confirmLabel: 'Open stop-signing review',
    },
    actions: [
      { id: 'scan-security-posture', label: 'Scan Security Posture', variant: 'lime' },
      { id: 'export-redacted-bundle', label: 'Export Redacted Bundle', variant: 'purple' },
    ],
  },
  identity: {
    key: 'identity',
    path: '/identity',
    icon: 'key',
    label: 'Identity + Keys',
    title: 'Identity + Keys',
    eyebrow: 'Key separation',
    description: 'Node identity, validator keys, reward keys, withdrawal authority, hardware signers, remote signer policy, and wallet tools.',
    jarvis: 'Keys are separated by role so operators do not confuse node identity, hot signing keys, cold withdrawal authority, and wallet accounts.',
    developerOnly: true,
    tone: 'purple',
    modeCopy: {
      basic: 'Readable wallet, receive/send, and which keys are safe to use.',
      advanced: 'Key roles, signer health, rotation status, address book, and transaction history.',
      developer: 'Key locations, permissions, derivation paths, remote signer TLS, and signing request previews.',
    },
    questions: [
      { label: 'Node identity', value: 'Present', tone: 'good', icon: 'badge' },
      { label: 'Remote signer', value: 'Active', tone: 'good', icon: 'lan' },
      { label: 'Key export', value: 'Guarded', tone: 'warn', icon: 'lock' },
    ],
    metrics: [
      { label: 'Key types', value: '7', detail: 'Separated authorities', tone: 'purple', icon: 'vpn_key' },
      { label: 'Signer latency', value: '12ms', detail: 'Remote approval path', tone: 'good', icon: 'speed' },
      { label: 'Wallet txs', value: '1,044', detail: 'Visible history', tone: 'cyan', icon: 'account_balance_wallet' },
      { label: 'File perms', value: '0600', detail: 'Private key storage', tone: 'good', icon: 'folder_secure' },
    ],
    checklistTitle: 'Key safety checklist',
    checklist: [
      { label: 'Hot and cold authorities separated', detail: 'Withdrawal authority is not used for routine signing.', done: true, tone: 'good' },
      { label: 'Hardware signer connected', detail: 'Ledger/HSM policy is reachable.', done: true, tone: 'good' },
      { label: 'Backup verification complete', detail: 'Restore phrase check requires operator review.', done: false, tone: 'warn' },
      { label: 'Clipboard protection enabled', detail: 'Sensitive copy operations require confirmation.', done: true, tone: 'good' },
    ],
    tableTitle: 'Key inventory',
    tableColumns: ['Authority', 'Location', 'Use', 'Status'],
    tableRows: [
      ['Node identity', 'Local keystore', 'P2P identity', 'Healthy'],
      ['Validator signing', 'Remote signer', 'Consensus duties', 'Active'],
      ['Reward address', 'Wallet', 'Payouts', 'Verified'],
      ['Withdrawal authority', 'Cold storage', 'Exits', 'Offline'],
    ],
    visual: 'identity',
    actions: [
      { id: 'audit-key-locations', label: 'Audit Key Locations', variant: 'blue' },
      { id: 'open-signing-preview', label: 'Open Signing Preview', variant: 'purple' },
    ],
  },
  api: {
    key: 'api',
    path: '/api',
    icon: 'terminal',
    label: 'API/RPC',
    title: 'Developer Tools & RPC Console',
    eyebrow: 'Local tooling',
    description: 'Raw RPC, query builder, transaction decoder, signature verifier, endpoint policy, and integration exports.',
    jarvis: 'Developer tools stay inside the same safety shell. Raw calls, decoders, and endpoint settings are visible without hiding network exposure risk.',
    tone: 'cyan',
    modeCopy: {
      basic: 'Safe endpoint status and generated examples.',
      advanced: 'Method controls, auth, CORS, rate limits, request health, and documentation exports.',
      developer: 'Raw JSON-RPC console, payload generator, decoder, signature verifier, and response inspector.',
    },
    questions: [
      { label: 'RPC status', value: 'Connected', tone: 'good', icon: 'lan' },
      { label: 'Current height', value: '18,492,051', tone: 'cyan', icon: 'height' },
      { label: 'Public exposure', value: 'Guarded', tone: 'good', icon: 'policy' },
    ],
    metrics: [
      { label: 'Request rate', value: '824/s', detail: 'All endpoints', tone: 'cyan', icon: 'monitoring' },
      { label: 'Error rate', value: '0.2%', detail: 'Last 15 minutes', tone: 'good', icon: 'check_circle' },
      { label: 'Slow queries', value: '3', detail: 'Archive required', tone: 'warn', icon: 'hourglass_bottom' },
      { label: 'API keys', value: '12', detail: 'Scoped credentials', tone: 'purple', icon: 'key' },
    ],
    checklistTitle: 'Endpoint readiness',
    checklist: [
      { label: 'Authentication enabled', detail: 'Admin and public API scopes are separated.', done: true, tone: 'good' },
      { label: 'Dangerous methods blocked', detail: 'Unsafe debug methods are not publicly exposed.', done: true, tone: 'good' },
      { label: 'CORS allowlist reviewed', detail: 'Allowed origins match operator policy.', done: true, tone: 'good' },
      { label: 'Archive method warnings active', detail: 'Expensive calls include node-role guidance.', done: true, tone: 'good' },
    ],
    tableTitle: 'Method usage analytics',
    tableColumns: ['Method', 'Rate', 'Latency', 'Policy'],
    tableRows: [
      ['synergy_getBlock', '244/s', '18ms', 'Allowed'],
      ['synergy_getPeerInfo', '14/s', '22ms', 'Local only'],
      ['eth_getLogs', '120/s', '184ms', 'Rate limited'],
      ['admin_stopSigning', '0/s', 'Blocked', 'Admin only'],
    ],
    visual: 'rpc',
    actions: [
      { id: 'generate-rpc-payload', label: 'Generate Payload', variant: 'blue' },
      { id: 'export-openapi', label: 'Export API Docs', variant: 'purple' },
    ],
  },
  maintenance: {
    key: 'maintenance',
    path: '/maintenance',
    icon: 'build_circle',
    label: 'Maintenance',
    title: 'Maintenance & Update Center',
    eyebrow: 'Safe changes',
    description: 'Signed updates, safe restart checks, hard fork countdowns, scheduled maintenance, diagnostics, and support bundles.',
    jarvis: 'Maintenance actions are duty-aware. The app should prefer safe windows, dry runs, backups, and explicit rollback guidance.',
    tone: 'cyan',
    modeCopy: {
      basic: 'Safe restart, update availability, and backup reminders.',
      advanced: 'Update workflow, migration preview, restart safety, maintenance windows, and diagnostics.',
      developer: 'Release metadata, binary hashes, schema migrations, config diffs, and rollback limitations.',
    },
    questions: [
      { label: 'Safe to restart', value: 'Yes', tone: 'good', icon: 'restart_alt' },
      { label: 'Network required', value: 'v9.0.16', tone: 'cyan', icon: 'system_update_alt' },
      { label: 'Hard fork', value: '14d', tone: 'warn', icon: 'event' },
    ],
    metrics: [
      { label: 'Current version', value: 'v9.0.16', detail: 'Installed app', tone: 'cyan', icon: 'deployed_code' },
      { label: 'Required version', value: 'v9.0.16', detail: 'Network policy', tone: 'good', icon: 'verified' },
      { label: 'Next duty', value: '14m', detail: 'Avoid restart before then', tone: 'warn', icon: 'schedule' },
      { label: 'Rollback', value: 'Prepared', detail: 'Config backup exists', tone: 'good', icon: 'restore' },
    ],
    checklistTitle: 'Update workflow',
    checklist: [
      { label: 'Binary signature verified', detail: 'Signed release metadata is valid.', done: true, tone: 'good' },
      { label: 'Configuration backup complete', detail: 'Diff is available before applying changes.', done: true, tone: 'good' },
      { label: 'Migration preview reviewed', detail: 'Database changes are visible before restart.', done: false, tone: 'warn' },
      { label: 'Duty-aware window selected', detail: 'Restart should wait for the safe interval.', done: true, tone: 'good' },
    ],
    tableTitle: 'Change log viewer',
    tableColumns: ['Release', 'Type', 'Risk', 'Operator note'],
    tableRows: [
      ['v9.0.16', 'Runtime', 'Low', 'Validator mesh and telemetry refinements'],
      ['v9.0.15', 'Control panel', 'Medium', 'Config migration required'],
      ['v9.0.14', 'Security', 'High', 'Signer policy update'],
      ['v9.0.13', 'RPC', 'Low', 'Method usage analytics'],
    ],
    visual: 'maintenance',
    actions: [
      { id: 'run-upgrade-dry-run', label: 'Run Upgrade Dry Run', variant: 'blue' },
      { id: 'schedule-maintenance', label: 'Schedule Maintenance', variant: 'purple' },
    ],
  },
  diagnostics: {
    key: 'diagnostics',
    path: '/diagnostics',
    icon: 'troubleshoot',
    label: 'Diagnostics',
    title: 'Diagnostics',
    eyebrow: 'Machine checks',
    description: 'Dedicated command-wall diagnostics for local process, ports, RPC, bootstrap, logs, disk, CPU, and support bundle state.',
    jarvis: 'Diagnostics keeps command-heavy machine checks out of Settings. Run one check, read the result, then move back to the normal workflow.',
    developerOnly: true,
    tone: 'warn',
    modeCopy: {
      developer: 'Port listeners, zombie processes, disk usage, local RPC tests, bootstrap probes, and log maintenance.',
    },
    questions: [
      { label: 'Port listeners', value: 'Inspectable', tone: 'cyan', icon: 'settings_ethernet' },
      { label: 'RPC checks', value: 'Ready', tone: 'good', icon: 'terminal' },
      { label: 'Support bundle', value: 'Available', tone: 'purple', icon: 'inventory_2' },
    ],
    metrics: [
      { label: 'Local processes', value: 'Tracked', detail: 'Control panel, service, and node runtime', tone: 'cyan', icon: 'memory' },
      { label: 'Disk usage', value: 'Check', detail: 'Workspace and snapshot footprint', tone: 'warn', icon: 'hard_drive' },
      { label: 'Bootstrap tests', value: 'Queued', detail: 'Bootnode and seed reachability probes', tone: 'purple', icon: 'hub' },
      { label: 'Log maintenance', value: 'Guarded', detail: 'Clearing logs stays explicit', tone: 'good', icon: 'receipt_long' },
    ],
    checklistTitle: 'Diagnostic workflow',
    checklist: [
      { label: 'Inspect listeners', detail: 'Confirm P2P and RPC ports match the selected node profile.', done: false, tone: 'cyan' },
      { label: 'Check stale processes', detail: 'Find zombie or duplicate runtime processes before restart plans.', done: false, tone: 'warn' },
      { label: 'Probe local RPC', detail: 'Verify local RPC responds before blaming upstream services.', done: false, tone: 'cyan' },
      { label: 'Prepare support bundle', detail: 'Collect redacted logs, config summary, and diagnostics metadata.', done: true, tone: 'good' },
    ],
    tableTitle: 'Command checks',
    tableColumns: ['Check', 'Input', 'Result', 'Next step'],
    tableRows: [
      ['Port listeners', '5620-5699', 'Not run', 'Run listener check'],
      ['Zombie processes', 'synergy-testbeta', 'Not run', 'Inspect process table'],
      ['Local RPC', '127.0.0.1', 'Not run', 'Send blockNumber probe'],
      ['Disk usage', 'workspace', 'Not run', 'Measure node folders'],
    ],
    visual: 'diagnostics',
    actions: [
      { id: 'run-diagnostics', label: 'Run Diagnostics', variant: 'blue' },
      { id: 'copy-support-bundle', label: 'Prepare Support Bundle', variant: 'purple' },
    ],
  },
  config: {
    key: 'config',
    path: '/config',
    icon: 'tune',
    label: 'Configuration',
    title: 'Configuration',
    eyebrow: 'Raw config',
    description: 'Raw configuration, environment, feature flags, bootstrap lists, diffing, and validation output.',
    jarvis: 'Configuration exposes raw values for developers. Proposed changes should be reviewed here, but applied only through guarded controls.',
    developerOnly: true,
    tone: 'purple',
    modeCopy: {
      developer: 'Raw config, feature flags, environment values, bootstrap lists, and config validation state.',
    },
    questions: [
      { label: 'Config file', value: 'Loaded', tone: 'cyan', icon: 'description' },
      { label: 'Feature flags', value: 'Inspectable', tone: 'purple', icon: 'flag' },
      { label: 'Validation', value: 'Pending', tone: 'warn', icon: 'rule' },
    ],
    metrics: [
      { label: 'Node profile', value: 'Validator', detail: 'Role and ports from node.toml', tone: 'cyan', icon: 'dns' },
      { label: 'Bootstrap list', value: 'Bundled', detail: 'Seed and bootnode config', tone: 'good', icon: 'hub' },
      { label: 'Feature flags', value: 'Visible', detail: 'Developer-only flag inventory', tone: 'purple', icon: 'flag' },
      { label: 'Validation', value: 'Review', detail: 'Schema and runtime checks', tone: 'warn', icon: 'fact_check' },
    ],
    checklistTitle: 'Config review',
    checklist: [
      { label: 'Confirm role selector', detail: 'Role must match this machine and one-node release model.', done: true, tone: 'good' },
      { label: 'Verify network ID', detail: 'Chain ID and genesis hash must match Testnet-Beta.', done: true, tone: 'good' },
      { label: 'Review bootstrap services', detail: 'Seed and bootnode endpoints should match the bundled setup package.', done: true, tone: 'cyan' },
      { label: 'Apply guarded change', detail: 'Runtime-impacting changes require normal UI confirmation.', done: false, tone: 'warn' },
    ],
    tableTitle: 'Config values',
    tableColumns: ['Key', 'Current value', 'Source', 'State'],
    tableRows: [
      ['chain_id', '338639', 'genesis.json', 'Locked'],
      ['rpc_port', '5640', 'node.toml', 'Review'],
      ['p2p_port', '5622', 'node.toml', 'Review'],
      ['developer_view', 'settings', 'localStorage', 'User controlled'],
    ],
    visual: 'config',
    actions: [
      { id: 'validate-config', label: 'Validate Config', variant: 'blue' },
      { id: 'copy-config-json', label: 'Copy Config JSON', variant: 'purple' },
    ],
  },
  governance: {
    key: 'governance',
    path: '/governance',
    icon: 'how_to_vote',
    label: 'Governance',
    title: 'Governance & Protocol Administration',
    eyebrow: 'Protocol decisions',
    description: 'Proposal feeds, vote deadlines, parameter diffs, software-upgrade proposals, and governance key separation.',
    jarvis: 'Governance ties operator action to protocol risk. Parameter changes and upgrade proposals need clear diffs before signing.',
    tone: 'cyan',
    modeCopy: {
      basic: 'Active proposals, deadlines, and whether a vote is needed.',
      advanced: 'Parameter diffs, quorum progress, turnout, vote history, and reminder scheduling.',
      developer: 'Raw proposal payloads, governance key policy, offline signing, and upgrade detection.',
    },
    questions: [
      { label: 'Active proposals', value: '3', tone: 'cyan', icon: 'ballot' },
      { label: 'Next deadline', value: '2d', tone: 'warn', icon: 'event' },
      { label: 'Quorum', value: '68%', tone: 'good', icon: 'groups' },
    ],
    metrics: [
      { label: 'Proposal turnout', value: '68%', detail: 'Current vote', tone: 'good', icon: 'groups' },
      { label: 'Passing projection', value: 'Yes', detail: 'Stake-weighted', tone: 'good', icon: 'thumb_up' },
      { label: 'Parameter diffs', value: '4', detail: 'Require review', tone: 'warn', icon: 'difference' },
      { label: 'Upgrade proposals', value: '1', detail: 'Software action', tone: 'purple', icon: 'system_update' },
    ],
    checklistTitle: 'Governance review',
    checklist: [
      { label: 'Proposal summary read', detail: 'Risk summary is attached to the vote builder.', done: true, tone: 'good' },
      { label: 'Parameter diff reviewed', detail: 'Gas limit and finality threshold changes are visible.', done: false, tone: 'warn' },
      { label: 'Governance key separated', detail: 'Voting authority is not the validator hot key.', done: true, tone: 'good' },
      { label: 'Reminder scheduled', detail: 'Deadline reminder is active.', done: true, tone: 'good' },
    ],
    tableTitle: 'Active proposal feed',
    tableColumns: ['Proposal', 'Type', 'Deadline', 'Status'],
    tableRows: [
      ['Adjust block size limit', 'Parameter', '2d 04h', 'Needs review'],
      ['Network upgrade Orion', 'Software', '5d 11h', 'Passing'],
      ['Treasury grant batch', 'Treasury', '6d 01h', 'Watching'],
      ['Validator metadata policy', 'Policy', '9d 22h', 'Open'],
    ],
    visual: 'governance',
    actions: [
      { id: 'open-vote-builder', label: 'Open Vote Builder', variant: 'blue' },
      { id: 'schedule-governance-reminder', label: 'Schedule Reminder', variant: 'purple' },
    ],
  },
  compliance: {
    key: 'compliance',
    path: '/compliance',
    icon: 'fact_check',
    label: 'Compliance',
    title: 'Compliance & Financial Reporting',
    eyebrow: 'Audit exports',
    description: 'Rewards, commission income, uptime, incidents, security events, governance votes, and redacted reporting packages.',
    jarvis: 'Compliance reports should be exportable without exposing secrets. Redacted support bundles and internal audit packages are separate paths.',
    tone: 'good',
    modeCopy: {
      basic: 'Downloadable reward and uptime summaries.',
      advanced: 'SLA, financial reports, incident history, governance votes, and audit trail exports.',
      developer: 'Machine-readable JSON, schema versions, redaction policy, and signed audit bundles.',
    },
    questions: [
      { label: 'Rewards report', value: 'Ready', tone: 'good', icon: 'summarize' },
      { label: 'SLA', value: '99.8%', tone: 'good', icon: 'verified' },
      { label: 'Open incidents', value: '0', tone: 'good', icon: 'task_alt' },
    ],
    metrics: [
      { label: 'Commission revenue', value: '142 SNRG', detail: 'Current period', tone: 'good', icon: 'savings' },
      { label: 'Reward rows', value: '927', detail: 'Exportable ledger', tone: 'cyan', icon: 'table_view' },
      { label: 'Audit events', value: '1,204', detail: 'Privileged actions', tone: 'purple', icon: 'history' },
      { label: 'Reports', value: '6', detail: 'Current quarter', tone: 'good', icon: 'description' },
    ],
    checklistTitle: 'Reporting package',
    checklist: [
      { label: 'Reward export generated', detail: 'CSV and JSON ledgers are available.', done: true, tone: 'good' },
      { label: 'SLA report assembled', detail: 'Uptime and missed duties are included.', done: true, tone: 'good' },
      { label: 'Redaction policy applied', detail: 'Secrets and sensitive endpoints are filtered.', done: true, tone: 'good' },
      { label: 'Internal audit bundle signed', detail: 'Signature verification remains to be run.', done: false, tone: 'warn' },
    ],
    tableTitle: 'Financial reports',
    tableColumns: ['Report', 'Period', 'Status', 'Export'],
    tableRows: [
      ['Tax statement', '2026', 'Ready', 'CSV'],
      ['Reward summary', 'Q2', 'Ready', 'PDF'],
      ['Commission history', 'Monthly', 'Ready', 'JSON'],
      ['Incident report', 'Quarterly', 'Ready', 'PDF'],
    ],
    visual: 'compliance',
    actions: [
      { id: 'export-financial-report', label: 'Export Financial Report', variant: 'lime' },
      { id: 'generate-audit-package', label: 'Generate Audit Package', variant: 'purple' },
    ],
  },
};

export const FEATURE_ROUTES = FEATURE_SCREEN_GROUPS
  .flatMap((group) => group.items)
  .map((key) => FEATURE_SCREENS[key])
  .filter(Boolean);

export function getFeatureScreenByKey(key) {
  return FEATURE_SCREENS[key] || null;
}

export function getFeatureScreenByPathname(pathname) {
  const normalizedPath = String(pathname || '').replace(/\/+$/, '') || '/';
  return FEATURE_ROUTES.find((screen) => normalizedPath === screen.path || normalizedPath.startsWith(`${screen.path}/`)) || null;
}

export function featureNavItemsForGroup(groupId) {
  const group = FEATURE_SCREEN_GROUPS.find((entry) => entry.id === groupId);
  if (!group) {
    return [];
  }
  return group.items.map((key) => FEATURE_SCREENS[key]).filter(Boolean);
}
